#!/bin/bash

VISUAL="vim"
export VISUAL
EDITOR="/bin/vi -e"
export EDITOR

export HISTSIZE=500000
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups

export POLYBAR_BARS="left right"
export POLYBAR_WLAN_INTERFACE="wlp5s0"
export POLYBAR_ETH_INTERFACE="enp6s0"

export DOCKER_SPOTIFY_FORCE_DEVICE_SCALE_FACTOR="2.0"
export DOCKER_SLACK_FORCE_DEVICE_SCALE_FACTOR="2.0"
